### ISSUE TITLE
How to use this, if its possible.

### ISSUE THREAD

**Issue by localuser-isback** [DinographicPixels/TouchGuild#53]
How to tell if an invite was create on the server? not an application invite but just a normal one.

**Comment by localuser-isback** [comment]
Is is also possible to remove that invite (with the bot)

**Comment by pakkographic** [comment]
Unfortunately, the Guilded API doesn't support server invites, it means that every Guilded library including TouchGuild won't be able to create and/or interact with server links. Please note that the Guilded API is still in beta which means this feature can be added in the future.

**Comment by pakkographic** [comment]
Anything else?

**Comment by localuser-isback** [comment]
Hm, is it possible to check when a user joined an guilded , if there username contails or is "x" for example, kick or ban them? Or if they send an application with that specific name deny it?

**Comment by pakkographic** [comment]
> Hm, is it possible to check when a user joined an guilded

You can check if a user joined a guild by using the [guildMemberAdd](https://docs.touchguild.com/v1.2.1/interfaces/Events.ClientEvents.html#guildMemberAdd) event, you can also check if a user left a guild by using [the guildMemberRemove](https://docs.touchguild.com/v1.2.1/interfaces/Events.ClientEvents.html#guildMemberRemove) event.

> "if there username contains or is "x" for example, kick or ban them?"
The events I listed above are providing enough information, including the ID of the member, the server they are in, their username, etc.. This allows you to kick or ban by using the correct methods which is Member#kick. Which means you need to get the Member component to kick/ban them. The guildMemberAdd event provides the Member component but the guildMemberRemove doesn't, but you can still get it by using the REST method (Client.rest.guilds#getMember) to kick/ban them.

> if they send an application with that specific name deny it?
There's multiple types of servers, private ones, application-only and public servers. If you need to kick or ban some of the members, check what I said above. If you're talking about managing member applications for now, the Guilded API doesn't support this feature, as for now.

**Comment by pakkographic** [comment]
I kindly suggest you to check the documentation before asking questions: https://docs.touchguild.com/
This could answer your own questions, by only typing "event" in the search bar to see the available events, and by only typing "member" it'd show you the actions you can perform on a Member component

**Comment by localuser-isback** [comment]
Alright, ive just never made a bot for guilded, when i tried doing this it didnt work but ill try again (and yes i did use the docs)
